### ISSUE TITLE
GeoIP2 Decoder usage example

### ISSUE THREAD

**Issue by Madhu1512** [mart1nl/heka-geoip2-decoder#1]
Hi there,

i used your instructions and compiled heka with geoip2-decoder plugin. now i am trying to decode the user location based on ip's from nginx access log but I have no success.

Here is my toml file

[Nginx-Webserver-Access]
type = "LogstreamerInput"
log_directory = "/home/guest"
file_match = 'test.log'
decoder = "shipped-nginx-decoder"

[shipped-nginx-decoder]
type = "MultiDecoder"
subs = ['CombinedLogDecoder', 'GeoIp2Decoder']

[CombinedLogDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/nginx_access.lua"

[CombinedLogDecoder.config]
type = "nginx.access"
user_agent_transform = true
# combined log format

log_format = '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'
payload_keep = true

[GeoIp2Decoder]
db_file = "/home/guest/GeoLite2-City.mmdb"
source_host_field = "remote_addr"
target_field_prefix = "geoip"
dns_lookup = false

[ESJsonEncoder]
index = "test-%{2006.01.02}"
es_index_from_timestamp = true
type_name = "%{Type}"
fields = ["Timestamp","Payload","HostName","Fields"]

[LogOutput]
message_matcher = "Type == 'nginx.access'"
encoder = "ESJsonEncoder"

Please let me know if am doing right way.

**Comment by loginoff** [comment]
Do you get an error message of some kind?
If the geoip fields don't show up, it might be that the IP addresses in your remote_addr field just are not found in the database (eg. private addresses).
Also, if your remote_addr field can also contain hostnames, then you can enable "dns_lookup = true" to lookup the IP address, but keep in mind that this is an expensive operation.

**Comment by Madhu1512** [comment]
I didn't got any error but i know some of the IP address are resolved when we used with logstash but not with heka and geoip2decoder. I will give a try again and let know the result. Do you see any issue with my toml config?

**Comment by loginoff** [comment]
Just by looking at your toml, nothing obviously erroneous pops into mind.
Do you have problems decoding just one IP or does the decoder return no results at all?

**Comment by Madhu1512** [comment]
The decoder returns no result at all

**Comment by loginoff** [comment]
Can you send me one line of input and the output corresponding to that line?

**Comment by Madhu1512** [comment]
Toml:

[Nginx-Webserver-Access]
type = "LogstreamerInput"
log_directory = "/home/guest"
file_match = 'test.log'
decoder = "CombinedLogDecoder"

[CombinedLogDecoder]
type = "SandboxDecoder"
filename = "lua_decoders/nginx_access.lua"

[CombinedLogDecoder.config]
type = "nginx.access"
user_agent_transform = true

# combined log format

log_format = '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent"'
payload_keep = true

[GeoIp2Decoder]
db_file = "/home/guest/GeoLite2-City.mmdb"
source_host_field = "remote_addr"
target_field_prefix = "geoip"
dns_lookup = false

[ESJsonEncoder]
index = "test-%{2006.01.02}"
es_index_from_timestamp = true
type_name = "%{Type}"
fields = ["Timestamp","Payload","HostName","Fields"]

[LogOutput]
message_matcher = "Type == 'nginx.access'"
encoder = "ESJsonEncoder"

input:

147.179.243.30 - - [26/Aug/2014:02:14:33 -0400] "GET /config.js HTTP/1.1" 301 184 "-" "Mozilla/4.0 (compatible;)"

output:

{"index":{"_index":"test-2014.08.26","_type":"nginx.access"}}
{"Timestamp":"2014-08-26T06:14:33.000Z","Payload":"147.179.243.30 - - [26/Aug/2014:02:14:33 -0400] \u0022GET /config.js HTTP/1.1\u0022 301 184 \u0022-\u0022 \u0022Mozilla/4.0 (compatible;)\u0022\u000a","HostName":"localhost","body_bytes_sent":184,"remote_addr":"147.179.243.30","status":301,"remote_user":"-","request":"GET /config.js HTTP/1.1","http_referer":"-"}
2015/03/05 12:46:17 {"index":{"_index":"test-2014.08.27","_type":"nginx.access"}}

**Comment by loginoff** [comment]
It actually might still be a configuration issue.
For your MultiDecoder, add: 
cascade_strategy = "all"

The default seems to be cascade_strategy = "first-wins" and this applies only the Nginx decoder, that's why you don't see any output from the GeoIp2Decoder.

**Comment by Madhu1512** [comment]
Thanks for the update. After adding the cascade_strategy = "all", i can decode the geoip locations.
